import { UserRole, RolePermissions } from '@/types';

export const ROLE_PERMISSIONS: Record<UserRole, RolePermissions> = {
  customer: {
    canViewOrders: true,
    canManageOrders: false,
    canViewDeliveries: true,
    canManageDeliveries: false,
    canViewReservations: true,
    canManageReservations: false,
    canViewReviews: true,
    canManageReviews: false,
    canViewQRCodes: false,
    canManageQRCodes: false,
    canViewMenu: true,
    canManageMenu: false,
    canViewUsers: false,
    canManageUsers: false,
    canManageRoles: false,
    canViewSettings: false,
    canManageSettings: false,
    canViewDashboard: false,
    canViewInternalOrders: false,
    canViewExternalOrders: false,
  },
  chef: {
    canViewOrders: true,
    canManageOrders: true,
    canViewDeliveries: false,
    canManageDeliveries: false,
    canViewReservations: false,
    canManageReservations: false,
    canViewReviews: false,
    canManageReviews: false,
    canViewQRCodes: false,
    canManageQRCodes: false,
    canViewMenu: false,
    canManageMenu: false,
    canViewUsers: false,
    canManageUsers: false,
    canManageRoles: false,
    canViewSettings: false,
    canManageSettings: false,
    canViewDashboard: true,
    canViewInternalOrders: true,
    canViewExternalOrders: true,
  },
  waiter: {
    canViewOrders: true,
    canManageOrders: true,
    canViewDeliveries: false,
    canManageDeliveries: false,
    canViewReservations: true,
    canManageReservations: false,
    canViewReviews: false,
    canManageReviews: false,
    canViewQRCodes: false,
    canManageQRCodes: false,
    canViewMenu: false,
    canManageMenu: false,
    canViewUsers: false,
    canManageUsers: false,
    canManageRoles: false,
    canViewSettings: false,
    canManageSettings: false,
    canViewDashboard: true,
    canViewInternalOrders: true,
    canViewExternalOrders: false,
  },
  courier: {
    canViewOrders: false,
    canManageOrders: false,
    canViewDeliveries: true,
    canManageDeliveries: true,
    canViewReservations: false,
    canManageReservations: false,
    canViewReviews: false,
    canManageReviews: false,
    canViewQRCodes: false,
    canManageQRCodes: false,
    canViewMenu: false,
    canManageMenu: false,
    canViewUsers: false,
    canManageUsers: false,
    canManageRoles: false,
    canViewSettings: false,
    canManageSettings: false,
    canViewDashboard: true,
    canViewInternalOrders: false,
    canViewExternalOrders: false,
  },
  moderator: {
    canViewOrders: true,
    canManageOrders: false,
    canViewDeliveries: false,
    canManageDeliveries: false,
    canViewReservations: true,
    canManageReservations: true,
    canViewReviews: true,
    canManageReviews: true,
    canViewQRCodes: true,
    canManageQRCodes: true,
    canViewMenu: false,
    canManageMenu: false,
    canViewUsers: false,
    canManageUsers: false,
    canManageRoles: false,
    canViewSettings: false,
    canManageSettings: false,
    canViewDashboard: true,
    canViewInternalOrders: true,
    canViewExternalOrders: true,
  },
  admin: {
    canViewOrders: true,
    canManageOrders: true,
    canViewDeliveries: true,
    canManageDeliveries: true,
    canViewReservations: true,
    canManageReservations: true,
    canViewReviews: true,
    canManageReviews: true,
    canViewQRCodes: true,
    canManageQRCodes: true,
    canViewMenu: true,
    canManageMenu: true,
    canViewUsers: true,
    canManageUsers: true,
    canManageRoles: true,
    canViewSettings: true,
    canManageSettings: true,
    canViewDashboard: true,
    canViewInternalOrders: true,
    canViewExternalOrders: true,
  },
};

export const hasPermission = (role: UserRole, permission: keyof RolePermissions): boolean => {
  return ROLE_PERMISSIONS[role][permission];
};

export const getRolePermissions = (role: UserRole): RolePermissions => {
  return ROLE_PERMISSIONS[role];
};

export const getRoleLabel = (role: UserRole): string => {
  const labels: Record<UserRole, string> = {
    customer: 'Müştəri',
    admin: 'Administrator',
    chef: 'Aşbaz',
    waiter: 'Ofisant',
    moderator: 'Moderator',
    courier: 'Kuryer',
  };
  return labels[role];
};

export const getRoleDashboardPath = (role: UserRole): string => {
  const paths: Record<UserRole, string> = {
    customer: '/',
    admin: '/admin',
    chef: '/chef',
    waiter: '/waiter',
    moderator: '/moderator',
    courier: '/courier',
  };
  return paths[role];
};
